### PR TITLE
aarch64

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@conda-forge-admin, please rerender

**Comment by whophil** [comment]
@conda-forge-admin, please restart ci

**Comment by adam-urbanczyk** [comment]
aarch64 fails with
```
import: 'OCP'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/ocp_1701963161212/test_tmp/run_test.py", line 2, in <module>
    import OCP
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

@whophil shall we disable testing for this platform? I don't how to continue otherwise and have no interest in digging into this.

**Comment by whophil** [comment]
@adam-urbanczyk seems like it's likely just a missing lib from the test environment. I'll try one thing (which I copied from the VTK feedstock). If it doesn't work, I am happy to revert and just skip the linux aarch64 test.

**Comment by whophil** [comment]
Replaced by #43

**Pull request closed without merging**
