### PR TITLE
Update to 7.7.0.0 (OCP 7.7.0)

### PR DESCRIPTION
**Pull request by whophil**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by whophil** [comment]
@adam-urbanczyk ARM and Win builds are failing on what seem to be VTK-finding issues. Do you have any insights?

**Comment by adam-urbanczyk** [comment]
Arm64 fails on vtk and I think I know how to fix it. Windows fails *after* building and testing of the package on "Prepare conda build artifacts". I don't understand how the pipeline works and ATM have no clue how to attack this issue.

**Comment by whophil** [comment]
@adam-urbanczyk the change I just pushed _should_ fix the issue with the build artifacts.

**Comment by whophil** [comment]
Thanks @adam-urbanczyk ! Looks like your changed worked. Merging

**Pull request merged**
