### PR TITLE
Fix occt pinning

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@conda-forge-admin, please rerender

**Comment by whophil** [comment]
Not sure if this will be necessary after merge https://github.com/conda-forge/occt-feedstock/pull/98 ?

**Comment by adam-urbanczyk** [comment]
I'd propose to merge this anyhow. OCP is meant to be used with exactly one version of OCCT.

**Review by whophil — APPROVED** [review]

**Comment by whophil** [comment]
> I'd propose to merge this anyhow. OCP is meant to be used with exactly one version of OCCT.
> 
> BTW: pin_subpackage(x.x.x) was already used/tried and it did not solve the issue. It could be a bug or my lack of understanding how it works.

Sounds good.

I had the same confusion about pin_subpackage(x.x.x). I believe it may be related to the fact that `occt` has a global pin with `pin_run_as_build` set to `x.x`. 

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml#L196-L197

I also posed the question on the conda-forge gitter, but have yet to receive a response which totally answers my question (see https://matrix.to/#/!SOyumkgPRWoXfQYIFH:matrix.org/$1682115377166wJxtR:gitter.im?via=matrix.org&via=gitter.im&via=cadair.com)

**Pull request merged**
