### PR TITLE
aarch64 attempt 2

### PR DESCRIPTION
**Pull request by whophil**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
@conda-forge-admin, please restart ci

**Comment by whophil** [comment]
@conda-forge-admin, please restart ci

**Comment by adam-urbanczyk** [comment]
IDK why, it did run till the end few times.

**Comment by whophil** [comment]
@conda-forge-admin, please restart ci

**Comment by whophil** [comment]
@adam-urbanczyk I think we can close #42 and merge this one instead.

1. linux aarch64 build is now finishing after adding some swap to the linux builder
2. linux aarch64 import test is now succeeding after changing `mesa-libGLU-devel` to `mesa-libGL-devel` in `yum_requirements.txt`

**Comment by adam-urbanczyk** [comment]
LGTM, thanks @whophil !

**Pull request merged**
